name: Build-and-Deploy

on:
  push:
    branches:
      - feat/issue#3/build-and-deploy
    workflow_dispatch:

jobs:

  Build-job:
    name: Build Job
    runs-on: 'ubuntu-latest'


    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install tree & run
        run: |
          sudo apt-get install -y tree
          tree .

      - name: Install Python
        run: |
          sudo apt-get install -y python3 python3-pip

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build
          python -m build
          tree .

      - name: Artifact Creation
        run: |
          rm dist/my_package-0.0.0.tar.gz
          mv script.py dist/script.py
          tree .

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist/*

  Deploy-job:
    name: Deploy Job
    needs: Build-job
    runs-on: 'ubuntu-latest'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my_artifact
          path: ./artifact








