name: Build and Deploy

on:
  push:
    branches:
      - feat/issue#3/build-and-deploy
    workflow_dispatch:

  jobs:

  with-checkout-job:
    name: With Checkout
    runs-on: 'ubuntu-latest'
    needs: without-checkout-job
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install tree & run
        run: |
          sudo apt-get install -y tree
          tree .

      - name: Install Build
        run: |
          sudo apt-get install -y python
          sudo apt-get install build
      - name: Build package
        run: |
          pip install --upgrade build
          python -m build
          tree .


